[package]
name = "opcua-logger"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
env_logger = "0.11.5"
opcua = { git = "https://github.com/centroid-is/opcua.git", branch = "master" }
tokio = "1.41.0"
